apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  selector:
    app: {{ .Chart.Name }}
