name: Docker Image CI

on:
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
